---
- name: Weave on AWS with Ansible Setup 
  hosts: localhost
  connection: local
  tags: provisioning
  vars:
    ssh_key: weavedemo
    aws_region: eu-west-1
    num_nodes: 1
    security_group_name: weavedemo
    template: ami-799e100e
    instance_type: m1.small

  roles:
    - common
    - weavedemo
    - dockerinstall
    - weaveinstall

    #  tasks: 
    # - name: Add new instance to host group
    #add_host: hostname="{{ item.public_ip }}" groupname=launched
    #with_items: ec2.instances

    #    - dockerinstall
    #- weaveinstall

    #- name: Install Docker on Hosts
    # hosts: launched 
    #sudo: yes
    #remote_user: ubuntu

    #  roles: 
    #- dockerinstall
    #- weaveinstall
